(cl:defpackage agv_control_msgs-srv
  (:use )
  (:export
   "COMMSTATUS"
   "<COMMSTATUS-REQUEST>"
   "COMMSTATUS-REQUEST"
   "<COMMSTATUS-RESPONSE>"
   "COMMSTATUS-RESPONSE"
   "GETMYPLAN"
   "<GETMYPLAN-REQUEST>"
   "GETMYPLAN-REQUEST"
   "<GETMYPLAN-RESPONSE>"
   "GETMYPLAN-RESPONSE"
   "REMOVAL"
   "<REMOVAL-REQUEST>"
   "REMOVAL-REQUEST"
   "<REMOVAL-RESPONSE>"
   "REMOVAL-RESPONSE"
   "SIGNBOARD"
   "<SIGNBOARD-REQUEST>"
   "SIGNBOARD-REQUEST"
   "<SIGNBOARD-RESPONSE>"
   "SIGNBOARD-RESPONSE"
  ))

