(cl:in-package agv_control_msgs-msg)
(cl:export '(VEHICLE_NAME-VAL
          VEHICLE_NAME
          PRIORITY-VAL
          PRIORITY
          CURR_SECTOR-VAL
          CURR_SECTOR
          ALLOCATED_SECTORS-VAL
          ALLOCATED_SECTORS
          GOAL_SECTOR-VAL
          GOAL_SECTOR
          GOAL_SEC_STATE-VAL
          GOAL_SEC_STATE
          GOAL_PZ-VAL
          GOAL_PZ
          GOAL_PZ_STATE-VAL
          GOAL_PZ_STATE
          PZ_CONTROL-VAL
          PZ_CONTROL
          ALLOCATED_NODE-VAL
          ALLOCATED_NODE
          REQUIRED_SEGMENTS-VAL
          REQUIRED_SEGMENTS
          ALLOCATED_SEGMENTS-VAL
          ALLOCATED_SEGMENTS
          CURR_PZ_SEQ-VAL
          CURR_PZ_SEQ
          MOVING-VAL
          MOVING
          REMOVING-VAL
          REMOVING
          DOCKING-VAL
          DOCKING
          PARKING-VAL
          PARKING
          PLANNING-VAL
          PLANNING
          PASSING-VAL
          PASSING
          INFAILURE-VAL
          INFAILURE
          IDLE-VAL
          IDLE
))