# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from agv_control_msgs/SignBoardRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SignBoardRequest(genpy.Message):
  _md5sum = "e2c42c1f23baba357f21a2e63400d4ff"
  _type = "agv_control_msgs/SignBoardRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """string vehicleName
"""
  __slots__ = ['vehicleName']
  _slot_types = ['string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vehicleName

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SignBoardRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.vehicleName is None:
        self.vehicleName = ''
    else:
      self.vehicleName = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.vehicleName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicleName = str[start:end].decode('utf-8')
      else:
        self.vehicleName = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.vehicleName
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicleName = str[start:end].decode('utf-8')
      else:
        self.vehicleName = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from agv_control_msgs/SignBoardResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import agv_control_msgs.msg
import geometry_msgs.msg
import std_msgs.msg

class SignBoardResponse(genpy.Message):
  _md5sum = "f685ac512ac397dbf6cdbaf3b356e604"
  _type = "agv_control_msgs/SignBoardResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """signBoardData sb_data


================================================================================
MSG: agv_control_msgs/signBoardData
string vehicle_name
int32 priority

string curr_sector
string[] allocated_sectors

string goal_sector
string goal_sec_state

geometry_msgs/PoseStamped goal_pz
string goal_pz_state
bool pz_control

geometry_msgs/PoseStamped allocated_node

uint32[] required_segments
uint32[] allocated_segments

uint32 curr_pz_seq

bool moving
bool removing
bool docking
bool parking
bool planning
bool passing
bool inFailure
bool idle

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['sb_data']
  _slot_types = ['agv_control_msgs/signBoardData']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sb_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SignBoardResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sb_data is None:
        self.sb_data = agv_control_msgs.msg.signBoardData()
    else:
      self.sb_data = agv_control_msgs.msg.signBoardData()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.sb_data.vehicle_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_i().pack(self.sb_data.priority))
      _x = self.sb_data.curr_sector
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.sb_data.allocated_sectors)
      buff.write(_struct_I.pack(length))
      for val1 in self.sb_data.allocated_sectors:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      _x = self.sb_data.goal_sector
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.sb_data.goal_sec_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.sb_data.goal_pz.header.seq, _x.sb_data.goal_pz.header.stamp.secs, _x.sb_data.goal_pz.header.stamp.nsecs))
      _x = self.sb_data.goal_pz.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.sb_data.goal_pz.pose.position.x, _x.sb_data.goal_pz.pose.position.y, _x.sb_data.goal_pz.pose.position.z, _x.sb_data.goal_pz.pose.orientation.x, _x.sb_data.goal_pz.pose.orientation.y, _x.sb_data.goal_pz.pose.orientation.z, _x.sb_data.goal_pz.pose.orientation.w))
      _x = self.sb_data.goal_pz_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.sb_data.pz_control, _x.sb_data.allocated_node.header.seq, _x.sb_data.allocated_node.header.stamp.secs, _x.sb_data.allocated_node.header.stamp.nsecs))
      _x = self.sb_data.allocated_node.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.sb_data.allocated_node.pose.position.x, _x.sb_data.allocated_node.pose.position.y, _x.sb_data.allocated_node.pose.position.z, _x.sb_data.allocated_node.pose.orientation.x, _x.sb_data.allocated_node.pose.orientation.y, _x.sb_data.allocated_node.pose.orientation.z, _x.sb_data.allocated_node.pose.orientation.w))
      length = len(self.sb_data.required_segments)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.sb_data.required_segments))
      length = len(self.sb_data.allocated_segments)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.pack(pattern, *self.sb_data.allocated_segments))
      _x = self
      buff.write(_get_struct_I8B().pack(_x.sb_data.curr_pz_seq, _x.sb_data.moving, _x.sb_data.removing, _x.sb_data.docking, _x.sb_data.parking, _x.sb_data.planning, _x.sb_data.passing, _x.sb_data.inFailure, _x.sb_data.idle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.sb_data is None:
        self.sb_data = agv_control_msgs.msg.signBoardData()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.vehicle_name = str[start:end].decode('utf-8')
      else:
        self.sb_data.vehicle_name = str[start:end]
      start = end
      end += 4
      (self.sb_data.priority,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.curr_sector = str[start:end].decode('utf-8')
      else:
        self.sb_data.curr_sector = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sb_data.allocated_sectors = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.sb_data.allocated_sectors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.goal_sector = str[start:end].decode('utf-8')
      else:
        self.sb_data.goal_sector = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.goal_sec_state = str[start:end].decode('utf-8')
      else:
        self.sb_data.goal_sec_state = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.sb_data.goal_pz.header.seq, _x.sb_data.goal_pz.header.stamp.secs, _x.sb_data.goal_pz.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.goal_pz.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.sb_data.goal_pz.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.sb_data.goal_pz.pose.position.x, _x.sb_data.goal_pz.pose.position.y, _x.sb_data.goal_pz.pose.position.z, _x.sb_data.goal_pz.pose.orientation.x, _x.sb_data.goal_pz.pose.orientation.y, _x.sb_data.goal_pz.pose.orientation.z, _x.sb_data.goal_pz.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.goal_pz_state = str[start:end].decode('utf-8')
      else:
        self.sb_data.goal_pz_state = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.sb_data.pz_control, _x.sb_data.allocated_node.header.seq, _x.sb_data.allocated_node.header.stamp.secs, _x.sb_data.allocated_node.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.sb_data.pz_control = bool(self.sb_data.pz_control)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.allocated_node.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.sb_data.allocated_node.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.sb_data.allocated_node.pose.position.x, _x.sb_data.allocated_node.pose.position.y, _x.sb_data.allocated_node.pose.position.z, _x.sb_data.allocated_node.pose.orientation.x, _x.sb_data.allocated_node.pose.orientation.y, _x.sb_data.allocated_node.pose.orientation.z, _x.sb_data.allocated_node.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.sb_data.required_segments = struct.unpack(pattern, str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.sb_data.allocated_segments = struct.unpack(pattern, str[start:end])
      _x = self
      start = end
      end += 12
      (_x.sb_data.curr_pz_seq, _x.sb_data.moving, _x.sb_data.removing, _x.sb_data.docking, _x.sb_data.parking, _x.sb_data.planning, _x.sb_data.passing, _x.sb_data.inFailure, _x.sb_data.idle,) = _get_struct_I8B().unpack(str[start:end])
      self.sb_data.moving = bool(self.sb_data.moving)
      self.sb_data.removing = bool(self.sb_data.removing)
      self.sb_data.docking = bool(self.sb_data.docking)
      self.sb_data.parking = bool(self.sb_data.parking)
      self.sb_data.planning = bool(self.sb_data.planning)
      self.sb_data.passing = bool(self.sb_data.passing)
      self.sb_data.inFailure = bool(self.sb_data.inFailure)
      self.sb_data.idle = bool(self.sb_data.idle)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.sb_data.vehicle_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      buff.write(_get_struct_i().pack(self.sb_data.priority))
      _x = self.sb_data.curr_sector
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      length = len(self.sb_data.allocated_sectors)
      buff.write(_struct_I.pack(length))
      for val1 in self.sb_data.allocated_sectors:
        length = len(val1)
        if python3 or type(val1) == unicode:
          val1 = val1.encode('utf-8')
          length = len(val1)
        buff.write(struct.pack('<I%ss'%length, length, val1))
      _x = self.sb_data.goal_sector
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.sb_data.goal_sec_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.sb_data.goal_pz.header.seq, _x.sb_data.goal_pz.header.stamp.secs, _x.sb_data.goal_pz.header.stamp.nsecs))
      _x = self.sb_data.goal_pz.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.sb_data.goal_pz.pose.position.x, _x.sb_data.goal_pz.pose.position.y, _x.sb_data.goal_pz.pose.position.z, _x.sb_data.goal_pz.pose.orientation.x, _x.sb_data.goal_pz.pose.orientation.y, _x.sb_data.goal_pz.pose.orientation.z, _x.sb_data.goal_pz.pose.orientation.w))
      _x = self.sb_data.goal_pz_state
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.sb_data.pz_control, _x.sb_data.allocated_node.header.seq, _x.sb_data.allocated_node.header.stamp.secs, _x.sb_data.allocated_node.header.stamp.nsecs))
      _x = self.sb_data.allocated_node.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.sb_data.allocated_node.pose.position.x, _x.sb_data.allocated_node.pose.position.y, _x.sb_data.allocated_node.pose.position.z, _x.sb_data.allocated_node.pose.orientation.x, _x.sb_data.allocated_node.pose.orientation.y, _x.sb_data.allocated_node.pose.orientation.z, _x.sb_data.allocated_node.pose.orientation.w))
      length = len(self.sb_data.required_segments)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.sb_data.required_segments.tostring())
      length = len(self.sb_data.allocated_segments)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.sb_data.allocated_segments.tostring())
      _x = self
      buff.write(_get_struct_I8B().pack(_x.sb_data.curr_pz_seq, _x.sb_data.moving, _x.sb_data.removing, _x.sb_data.docking, _x.sb_data.parking, _x.sb_data.planning, _x.sb_data.passing, _x.sb_data.inFailure, _x.sb_data.idle))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.sb_data is None:
        self.sb_data = agv_control_msgs.msg.signBoardData()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.vehicle_name = str[start:end].decode('utf-8')
      else:
        self.sb_data.vehicle_name = str[start:end]
      start = end
      end += 4
      (self.sb_data.priority,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.curr_sector = str[start:end].decode('utf-8')
      else:
        self.sb_data.curr_sector = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.sb_data.allocated_sectors = []
      for i in range(0, length):
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1 = str[start:end].decode('utf-8')
        else:
          val1 = str[start:end]
        self.sb_data.allocated_sectors.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.goal_sector = str[start:end].decode('utf-8')
      else:
        self.sb_data.goal_sector = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.goal_sec_state = str[start:end].decode('utf-8')
      else:
        self.sb_data.goal_sec_state = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.sb_data.goal_pz.header.seq, _x.sb_data.goal_pz.header.stamp.secs, _x.sb_data.goal_pz.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.goal_pz.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.sb_data.goal_pz.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.sb_data.goal_pz.pose.position.x, _x.sb_data.goal_pz.pose.position.y, _x.sb_data.goal_pz.pose.position.z, _x.sb_data.goal_pz.pose.orientation.x, _x.sb_data.goal_pz.pose.orientation.y, _x.sb_data.goal_pz.pose.orientation.z, _x.sb_data.goal_pz.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.goal_pz_state = str[start:end].decode('utf-8')
      else:
        self.sb_data.goal_pz_state = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.sb_data.pz_control, _x.sb_data.allocated_node.header.seq, _x.sb_data.allocated_node.header.stamp.secs, _x.sb_data.allocated_node.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.sb_data.pz_control = bool(self.sb_data.pz_control)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.sb_data.allocated_node.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.sb_data.allocated_node.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.sb_data.allocated_node.pose.position.x, _x.sb_data.allocated_node.pose.position.y, _x.sb_data.allocated_node.pose.position.z, _x.sb_data.allocated_node.pose.orientation.x, _x.sb_data.allocated_node.pose.orientation.y, _x.sb_data.allocated_node.pose.orientation.z, _x.sb_data.allocated_node.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.sb_data.required_segments = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      end += struct.calcsize(pattern)
      self.sb_data.allocated_segments = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      _x = self
      start = end
      end += 12
      (_x.sb_data.curr_pz_seq, _x.sb_data.moving, _x.sb_data.removing, _x.sb_data.docking, _x.sb_data.parking, _x.sb_data.planning, _x.sb_data.passing, _x.sb_data.inFailure, _x.sb_data.idle,) = _get_struct_I8B().unpack(str[start:end])
      self.sb_data.moving = bool(self.sb_data.moving)
      self.sb_data.removing = bool(self.sb_data.removing)
      self.sb_data.docking = bool(self.sb_data.docking)
      self.sb_data.parking = bool(self.sb_data.parking)
      self.sb_data.planning = bool(self.sb_data.planning)
      self.sb_data.passing = bool(self.sb_data.passing)
      self.sb_data.inFailure = bool(self.sb_data.inFailure)
      self.sb_data.idle = bool(self.sb_data.idle)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_I8B = None
def _get_struct_I8B():
    global _struct_I8B
    if _struct_I8B is None:
        _struct_I8B = struct.Struct("<I8B")
    return _struct_I8B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
class SignBoard(object):
  _type          = 'agv_control_msgs/SignBoard'
  _md5sum = '390ca359a372ba93439ce72b36acb943'
  _request_class  = SignBoardRequest
  _response_class = SignBoardResponse
