// Generated by gencpp from file agv_control_msgs/CommStatusResponse.msg
// DO NOT EDIT!


#ifndef AGV_CONTROL_MSGS_MESSAGE_COMMSTATUSRESPONSE_H
#define AGV_CONTROL_MSGS_MESSAGE_COMMSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_control_msgs
{
template <class ContainerAllocator>
struct CommStatusResponse_
{
  typedef CommStatusResponse_<ContainerAllocator> Type;

  CommStatusResponse_()
    : response(false)  {
    }
  CommStatusResponse_(const ContainerAllocator& _alloc)
    : response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommStatusResponse_

typedef ::agv_control_msgs::CommStatusResponse_<std::allocator<void> > CommStatusResponse;

typedef boost::shared_ptr< ::agv_control_msgs::CommStatusResponse > CommStatusResponsePtr;
typedef boost::shared_ptr< ::agv_control_msgs::CommStatusResponse const> CommStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_control_msgs::CommStatusResponse_<ContainerAllocator1> & lhs, const ::agv_control_msgs::CommStatusResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_control_msgs::CommStatusResponse_<ContainerAllocator1> & lhs, const ::agv_control_msgs::CommStatusResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::agv_control_msgs::CommStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003b81baa95ab323ULL;
  static const uint64_t static_value2 = 0xfc1ddf3c7d0bee81ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_control_msgs/CommStatusResponse";
  }

  static const char* value(const ::agv_control_msgs::CommStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool response\n"
"\n"
;
  }

  static const char* value(const ::agv_control_msgs::CommStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_control_msgs::CommStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_control_msgs::CommStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_CONTROL_MSGS_MESSAGE_COMMSTATUSRESPONSE_H
