// Generated by gencpp from file agv_control_msgs/CommStatus.msg
// DO NOT EDIT!


#ifndef AGV_CONTROL_MSGS_MESSAGE_COMMSTATUS_H
#define AGV_CONTROL_MSGS_MESSAGE_COMMSTATUS_H

#include <ros/service_traits.h>


#include <agv_control_msgs/CommStatusRequest.h>
#include <agv_control_msgs/CommStatusResponse.h>


namespace agv_control_msgs
{

struct CommStatus
{

typedef CommStatusRequest Request;
typedef CommStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommStatus
} // namespace agv_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_control_msgs::CommStatus > {
  static const char* value()
  {
    return "506f41635c0339e93c963a71da685d19";
  }

  static const char* value(const ::agv_control_msgs::CommStatus&) { return value(); }
};

template<>
struct DataType< ::agv_control_msgs::CommStatus > {
  static const char* value()
  {
    return "agv_control_msgs/CommStatus";
  }

  static const char* value(const ::agv_control_msgs::CommStatus&) { return value(); }
};


// service_traits::MD5Sum< ::agv_control_msgs::CommStatusRequest> should match
// service_traits::MD5Sum< ::agv_control_msgs::CommStatus >
template<>
struct MD5Sum< ::agv_control_msgs::CommStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_control_msgs::CommStatus >::value();
  }
  static const char* value(const ::agv_control_msgs::CommStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_control_msgs::CommStatusRequest> should match
// service_traits::DataType< ::agv_control_msgs::CommStatus >
template<>
struct DataType< ::agv_control_msgs::CommStatusRequest>
{
  static const char* value()
  {
    return DataType< ::agv_control_msgs::CommStatus >::value();
  }
  static const char* value(const ::agv_control_msgs::CommStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_control_msgs::CommStatusResponse> should match
// service_traits::MD5Sum< ::agv_control_msgs::CommStatus >
template<>
struct MD5Sum< ::agv_control_msgs::CommStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_control_msgs::CommStatus >::value();
  }
  static const char* value(const ::agv_control_msgs::CommStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_control_msgs::CommStatusResponse> should match
// service_traits::DataType< ::agv_control_msgs::CommStatus >
template<>
struct DataType< ::agv_control_msgs::CommStatusResponse>
{
  static const char* value()
  {
    return DataType< ::agv_control_msgs::CommStatus >::value();
  }
  static const char* value(const ::agv_control_msgs::CommStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_CONTROL_MSGS_MESSAGE_COMMSTATUS_H
