// Generated by gencpp from file agv_control_msgs/GetMyPlan.msg
// DO NOT EDIT!


#ifndef AGV_CONTROL_MSGS_MESSAGE_GETMYPLAN_H
#define AGV_CONTROL_MSGS_MESSAGE_GETMYPLAN_H

#include <ros/service_traits.h>


#include <agv_control_msgs/GetMyPlanRequest.h>
#include <agv_control_msgs/GetMyPlanResponse.h>


namespace agv_control_msgs
{

struct GetMyPlan
{

typedef GetMyPlanRequest Request;
typedef GetMyPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMyPlan
} // namespace agv_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_control_msgs::GetMyPlan > {
  static const char* value()
  {
    return "fafb7a48c36f2c02adeb6df2d676b49e";
  }

  static const char* value(const ::agv_control_msgs::GetMyPlan&) { return value(); }
};

template<>
struct DataType< ::agv_control_msgs::GetMyPlan > {
  static const char* value()
  {
    return "agv_control_msgs/GetMyPlan";
  }

  static const char* value(const ::agv_control_msgs::GetMyPlan&) { return value(); }
};


// service_traits::MD5Sum< ::agv_control_msgs::GetMyPlanRequest> should match
// service_traits::MD5Sum< ::agv_control_msgs::GetMyPlan >
template<>
struct MD5Sum< ::agv_control_msgs::GetMyPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_control_msgs::GetMyPlan >::value();
  }
  static const char* value(const ::agv_control_msgs::GetMyPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_control_msgs::GetMyPlanRequest> should match
// service_traits::DataType< ::agv_control_msgs::GetMyPlan >
template<>
struct DataType< ::agv_control_msgs::GetMyPlanRequest>
{
  static const char* value()
  {
    return DataType< ::agv_control_msgs::GetMyPlan >::value();
  }
  static const char* value(const ::agv_control_msgs::GetMyPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_control_msgs::GetMyPlanResponse> should match
// service_traits::MD5Sum< ::agv_control_msgs::GetMyPlan >
template<>
struct MD5Sum< ::agv_control_msgs::GetMyPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_control_msgs::GetMyPlan >::value();
  }
  static const char* value(const ::agv_control_msgs::GetMyPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_control_msgs::GetMyPlanResponse> should match
// service_traits::DataType< ::agv_control_msgs::GetMyPlan >
template<>
struct DataType< ::agv_control_msgs::GetMyPlanResponse>
{
  static const char* value()
  {
    return DataType< ::agv_control_msgs::GetMyPlan >::value();
  }
  static const char* value(const ::agv_control_msgs::GetMyPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_CONTROL_MSGS_MESSAGE_GETMYPLAN_H
