// Generated by gencpp from file agv_control_msgs/Removal.msg
// DO NOT EDIT!


#ifndef AGV_CONTROL_MSGS_MESSAGE_REMOVAL_H
#define AGV_CONTROL_MSGS_MESSAGE_REMOVAL_H

#include <ros/service_traits.h>


#include <agv_control_msgs/RemovalRequest.h>
#include <agv_control_msgs/RemovalResponse.h>


namespace agv_control_msgs
{

struct Removal
{

typedef RemovalRequest Request;
typedef RemovalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Removal
} // namespace agv_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_control_msgs::Removal > {
  static const char* value()
  {
    return "d5f813c7363f04e91a9f024e37136d87";
  }

  static const char* value(const ::agv_control_msgs::Removal&) { return value(); }
};

template<>
struct DataType< ::agv_control_msgs::Removal > {
  static const char* value()
  {
    return "agv_control_msgs/Removal";
  }

  static const char* value(const ::agv_control_msgs::Removal&) { return value(); }
};


// service_traits::MD5Sum< ::agv_control_msgs::RemovalRequest> should match
// service_traits::MD5Sum< ::agv_control_msgs::Removal >
template<>
struct MD5Sum< ::agv_control_msgs::RemovalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_control_msgs::Removal >::value();
  }
  static const char* value(const ::agv_control_msgs::RemovalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_control_msgs::RemovalRequest> should match
// service_traits::DataType< ::agv_control_msgs::Removal >
template<>
struct DataType< ::agv_control_msgs::RemovalRequest>
{
  static const char* value()
  {
    return DataType< ::agv_control_msgs::Removal >::value();
  }
  static const char* value(const ::agv_control_msgs::RemovalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_control_msgs::RemovalResponse> should match
// service_traits::MD5Sum< ::agv_control_msgs::Removal >
template<>
struct MD5Sum< ::agv_control_msgs::RemovalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_control_msgs::Removal >::value();
  }
  static const char* value(const ::agv_control_msgs::RemovalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_control_msgs::RemovalResponse> should match
// service_traits::DataType< ::agv_control_msgs::Removal >
template<>
struct DataType< ::agv_control_msgs::RemovalResponse>
{
  static const char* value()
  {
    return DataType< ::agv_control_msgs::Removal >::value();
  }
  static const char* value(const ::agv_control_msgs::RemovalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_CONTROL_MSGS_MESSAGE_REMOVAL_H
