// Generated by gencpp from file agv_control_msgs/SignBoardResponse.msg
// DO NOT EDIT!


#ifndef AGV_CONTROL_MSGS_MESSAGE_SIGNBOARDRESPONSE_H
#define AGV_CONTROL_MSGS_MESSAGE_SIGNBOARDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <agv_control_msgs/signBoardData.h>

namespace agv_control_msgs
{
template <class ContainerAllocator>
struct SignBoardResponse_
{
  typedef SignBoardResponse_<ContainerAllocator> Type;

  SignBoardResponse_()
    : sb_data()  {
    }
  SignBoardResponse_(const ContainerAllocator& _alloc)
    : sb_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::agv_control_msgs::signBoardData_<ContainerAllocator>  _sb_data_type;
  _sb_data_type sb_data;





  typedef boost::shared_ptr< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SignBoardResponse_

typedef ::agv_control_msgs::SignBoardResponse_<std::allocator<void> > SignBoardResponse;

typedef boost::shared_ptr< ::agv_control_msgs::SignBoardResponse > SignBoardResponsePtr;
typedef boost::shared_ptr< ::agv_control_msgs::SignBoardResponse const> SignBoardResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_control_msgs::SignBoardResponse_<ContainerAllocator1> & lhs, const ::agv_control_msgs::SignBoardResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sb_data == rhs.sb_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_control_msgs::SignBoardResponse_<ContainerAllocator1> & lhs, const ::agv_control_msgs::SignBoardResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f685ac512ac397dbf6cdbaf3b356e604";
  }

  static const char* value(const ::agv_control_msgs::SignBoardResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf685ac512ac397dbULL;
  static const uint64_t static_value2 = 0xf6cdbaf3b356e604ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_control_msgs/SignBoardResponse";
  }

  static const char* value(const ::agv_control_msgs::SignBoardResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "signBoardData sb_data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: agv_control_msgs/signBoardData\n"
"string vehicle_name\n"
"int32 priority\n"
"\n"
"string curr_sector\n"
"string[] allocated_sectors\n"
"\n"
"string goal_sector\n"
"string goal_sec_state\n"
"\n"
"geometry_msgs/PoseStamped goal_pz\n"
"string goal_pz_state\n"
"bool pz_control\n"
"\n"
"geometry_msgs/PoseStamped allocated_node\n"
"\n"
"uint32[] required_segments\n"
"uint32[] allocated_segments\n"
"\n"
"uint32 curr_pz_seq\n"
"\n"
"bool moving\n"
"bool removing\n"
"bool docking\n"
"bool parking\n"
"bool planning\n"
"bool passing\n"
"bool inFailure\n"
"bool idle\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::agv_control_msgs::SignBoardResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sb_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SignBoardResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_control_msgs::SignBoardResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_control_msgs::SignBoardResponse_<ContainerAllocator>& v)
  {
    s << indent << "sb_data: ";
    s << std::endl;
    Printer< ::agv_control_msgs::signBoardData_<ContainerAllocator> >::stream(s, indent + "  ", v.sb_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_CONTROL_MSGS_MESSAGE_SIGNBOARDRESPONSE_H
