// Generated by gencpp from file agv_control_msgs/SignBoard.msg
// DO NOT EDIT!


#ifndef AGV_CONTROL_MSGS_MESSAGE_SIGNBOARD_H
#define AGV_CONTROL_MSGS_MESSAGE_SIGNBOARD_H

#include <ros/service_traits.h>


#include <agv_control_msgs/SignBoardRequest.h>
#include <agv_control_msgs/SignBoardResponse.h>


namespace agv_control_msgs
{

struct SignBoard
{

typedef SignBoardRequest Request;
typedef SignBoardResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SignBoard
} // namespace agv_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_control_msgs::SignBoard > {
  static const char* value()
  {
    return "390ca359a372ba93439ce72b36acb943";
  }

  static const char* value(const ::agv_control_msgs::SignBoard&) { return value(); }
};

template<>
struct DataType< ::agv_control_msgs::SignBoard > {
  static const char* value()
  {
    return "agv_control_msgs/SignBoard";
  }

  static const char* value(const ::agv_control_msgs::SignBoard&) { return value(); }
};


// service_traits::MD5Sum< ::agv_control_msgs::SignBoardRequest> should match
// service_traits::MD5Sum< ::agv_control_msgs::SignBoard >
template<>
struct MD5Sum< ::agv_control_msgs::SignBoardRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_control_msgs::SignBoard >::value();
  }
  static const char* value(const ::agv_control_msgs::SignBoardRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_control_msgs::SignBoardRequest> should match
// service_traits::DataType< ::agv_control_msgs::SignBoard >
template<>
struct DataType< ::agv_control_msgs::SignBoardRequest>
{
  static const char* value()
  {
    return DataType< ::agv_control_msgs::SignBoard >::value();
  }
  static const char* value(const ::agv_control_msgs::SignBoardRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_control_msgs::SignBoardResponse> should match
// service_traits::MD5Sum< ::agv_control_msgs::SignBoard >
template<>
struct MD5Sum< ::agv_control_msgs::SignBoardResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_control_msgs::SignBoard >::value();
  }
  static const char* value(const ::agv_control_msgs::SignBoardResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_control_msgs::SignBoardResponse> should match
// service_traits::DataType< ::agv_control_msgs::SignBoard >
template<>
struct DataType< ::agv_control_msgs::SignBoardResponse>
{
  static const char* value()
  {
    return DataType< ::agv_control_msgs::SignBoard >::value();
  }
  static const char* value(const ::agv_control_msgs::SignBoardResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_CONTROL_MSGS_MESSAGE_SIGNBOARD_H
