// Generated by gencpp from file agv_control_msgs/stringArray.msg
// DO NOT EDIT!


#ifndef AGV_CONTROL_MSGS_MESSAGE_STRINGARRAY_H
#define AGV_CONTROL_MSGS_MESSAGE_STRINGARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_control_msgs
{
template <class ContainerAllocator>
struct stringArray_
{
  typedef stringArray_<ContainerAllocator> Type;

  stringArray_()
    : data()  {
    }
  stringArray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::agv_control_msgs::stringArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_control_msgs::stringArray_<ContainerAllocator> const> ConstPtr;

}; // struct stringArray_

typedef ::agv_control_msgs::stringArray_<std::allocator<void> > stringArray;

typedef boost::shared_ptr< ::agv_control_msgs::stringArray > stringArrayPtr;
typedef boost::shared_ptr< ::agv_control_msgs::stringArray const> stringArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_control_msgs::stringArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_control_msgs::stringArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_control_msgs::stringArray_<ContainerAllocator1> & lhs, const ::agv_control_msgs::stringArray_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_control_msgs::stringArray_<ContainerAllocator1> & lhs, const ::agv_control_msgs::stringArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agv_control_msgs::stringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_control_msgs::stringArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_control_msgs::stringArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_control_msgs::stringArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_control_msgs::stringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_control_msgs::stringArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_control_msgs::stringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cce5a364f3a3be12c9722c6dcad2fa94";
  }

  static const char* value(const ::agv_control_msgs::stringArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcce5a364f3a3be12ULL;
  static const uint64_t static_value2 = 0xc9722c6dcad2fa94ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_control_msgs::stringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_control_msgs/stringArray";
  }

  static const char* value(const ::agv_control_msgs::stringArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_control_msgs::stringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] data\n"
;
  }

  static const char* value(const ::agv_control_msgs::stringArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_control_msgs::stringArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stringArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_control_msgs::stringArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_control_msgs::stringArray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_CONTROL_MSGS_MESSAGE_STRINGARRAY_H
